### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by vasesen** [jinzhubaofu/san-mui-examples#2]
运行时报错

**Comment by Leaf217** [comment]
run不起来？报错大概都是这样的（好多条）：
`ERROR in ./node_modules/san-mui/es/DatePicker/DatePicker.js
Module parse failed: /Users/zhu_yeqing/Desktop/san-mui-examples/san-mui-with-webpack/node_modules/san-mui/es/DatePicker/DatePicker.js Unexpected token (21:20)
You may need an appropriate loader to handle this file type.
| export default class DatePicker extends Component {
|
|     static template = `
|         <div class="sm-date-picker" ref="anchor">
|             <san-text-field
 @ ./node_modules/san-mui/es/DatePicker/index.js 6:0-38
 @ ./node_modules/san-mui/es/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js`

**Comment by vasesen** [comment]
>           运行时报错
